### ISSUE TITLE
where is the ms_train.h5ad

### ISSUE THREAD

**Issue by Cartride** [SabbaghCodes/ImbalancedLearningForSingleCellFoundationModels#1]
hope your reply

**Comment by SabbaghCodes** [comment]
Hi, 
`ms_train.h5ad` is the same as `ms_default.h5ad` before conventionally naming it. You can find the file inside this [link](https://drive.google.com/drive/u/3/folders/1bNOrB0ukkAuGtcocdvctSVOaAUG6uJ8l). 

Sorry for the inconvenience and thank you for your interest in running the experiments!
